<Project>
  <PropertyGroup>
    <IsLinux>false</IsLinux>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Miningcore'">
    <Compile Remove="$(MSBuildProjectDirectory)/Blockchain/Bitcoin/MergedMining/MergedMiningManagerUpdateDiagnostic.cs" />
    <Compile Remove="$(MSBuildProjectDirectory)/Blockchain/Bitcoin/MergedMining/MergedMiningManagerNewnessDiagnostic.cs" />
    <Compile Remove="$(MSBuildProjectDirectory)/Blockchain/Bitcoin/MergedMining/MergedMiningBitcoinPool.cs" />
  </ItemGroup>
</Project>
